# Generated by Django 2.2.10 on 2020-03-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mailid',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
