# Generated by Django 2.2.10 on 2020-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_mailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='commque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=250, null=True)),
                ('quetype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='techque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=250, null=True)),
                ('quetype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
