# Generated by Django 2.2.10 on 2020-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200307_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Score',
            new_name='writeuperrors',
        ),
    ]
