# Generated by Django 2.2.10 on 2020-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200308_2050'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='techque',
            name='sample1',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='techque',
            name='sample2',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='techque',
            name='sample3',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
