# Generated by Django 2.2.10 on 2020-03-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='score',
            new_name='Score',
        ),
    ]
