# Generated by Django 2.2.10 on 2020-03-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200308_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Score',
        ),
    ]
