# Generated by Django 2.2.10 on 2020-03-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200309_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='networkscore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='oopsscore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='progscore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
