# Generated by Django 2.2.10 on 2020-05-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200310_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Department',
        ),
    ]
