# Generated by Django 2.2.12 on 2020-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Fathername', models.CharField(blank=True, max_length=200, null=True)),
                ('collegeid', models.CharField(blank=True, max_length=200, null=True)),
                ('collegename', models.CharField(blank=True, max_length=200, null=True)),
                ('Department', models.CharField(default='cse', max_length=70)),
                ('mailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('writeuperrors', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=250, null=True)),
                ('progscore', models.IntegerField(blank=True, null=True)),
                ('networkscore', models.IntegerField(blank=True, null=True)),
                ('oopsscore', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
